apiVersion: v1
kind: Secret
metadata:
  name: flinox-ksqldb-server
  namespace: flinox-ksqldb-server
type: Opaque
stringData:
  KSQL_LISTENERS: http://0.0.0.0:8088
  KSQL_BOOTSTRAP_SERVERS: #{KC-URL}#
  KSQL_KSQL_INTERNAL_TOPIC_REPLICAS: "3"
  KSQL_KSQL_SINK_REPLICAS: "3"
  KSQL_KSQL_STREAMS_REPLICATION_FACTOR: "3"
  KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: "3"
  KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "false"
  KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "false"
  KSQL_SECURITY_PROTOCOL: SASL_SSL
  KSQL_SASL_MECHANISM: PLAIN
  KSQL_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"#{KC-KC-KEY}#\" password=\"#{KC-KC-SECRET}#\";"
  KSQL_KSQL_SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
  KSQL_KSQL_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: #{SR-KC-KEY}#:#{SR-KC-SECRET}#
  KSQL_KSQL_SCHEMA_REGISTRY_URL: #{SR-URL}#
  TZ: America/Sao_Paulo
