apiVersion: v1
kind: Service
metadata:
  name: flinox-ksqldb-server
  namespace: flinox-ksqldb-server
spec:
  type: NodePort
  selector:
    app: flinox-ksqldb-server
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
    
