#!/bin/bash

# API E SECRET DO SCHEMA REGISTRY ( AMBIENTE DE HML )
export SR_API_KEY=XXXXXXXXXXXXXXXXXXXXX
export SR_API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
export SR_URL=https://yyyy-xxxxx.westus2.azure.confluent.cloud

# API E SECRET DO KAFKA CLUSTER ( AMBIENTE DE HML )
export KC_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXX
export KC_API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
export KC_URL=https://yyyyy-xxxxx.brazilsouth.azure.confluent.cloud:9092