#!/bin/bash

# API E SECRET DO SCHEMA REGISTRY ( AMBIENTE DE DEV )
export SR_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXX
export SR_API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
export SR_URL=https://yyyyy-xxxxx.westus2.azure.confluent.cloud

# API E SECRET DO KAFKA CLUSTER ( AMBIENTE DE DEV )
export KC_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
export KC_API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
export KC_URL=https://yyyy-xxxxx.eastus.azure.confluent.cloud:9092